# ==================================================
# Takhlees Tech Backend - Development Override Configuration
# ==================================================
# This file overrides the base docker-compose.yml for development
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml --env-file .env.dev up -d

services:
  # ========================================
  # Database Services - Development Overrides
  # ========================================
  
  # Admin Database - Development Settings
  admin-db:
    ports:
      - "${ADMIN_DB_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_DB_ROOT_PASSWORD:-dev_admin_root}
      MYSQL_DATABASE: ${ADMIN_DB_NAME:-dev_logs}
      MYSQL_USER: ${ADMIN_DB_USER:-dev_admin}
      MYSQL_PASSWORD: ${ADMIN_DB_PASSWORD:-dev_admin_pass}
    volumes:
      - admin_db_dev_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  # CustomerService Database - Development Settings
  customerservice-db:
    ports:
      - "${CUSTOMERSERVICE_DB_PORT:-3308}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${CUSTOMERSERVICE_DB_ROOT_PASSWORD:-dev_customerservice_root}
      MYSQL_DATABASE: ${CUSTOMERSERVICE_DB_NAME:-dev_CustomerService}
      MYSQL_USER: ${CUSTOMERSERVICE_DB_USER:-dev_customerservice}
      MYSQL_PASSWORD: ${CUSTOMERSERVICE_DB_PASSWORD:-dev_customerservice_pass}
    volumes:
      - customerservice_db_dev_data:/var/lib/mysql

  # FirstProject Database - Development Settings
  firstproject-db:
    ports:
      - "${FIRSTPROJECT_DB_PORT:-3309}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${FIRSTPROJECT_DB_ROOT_PASSWORD:-dev_firstproject_root}
      MYSQL_DATABASE: ${FIRSTPROJECT_DB_NAME:-dev_mainData}
      MYSQL_USER: ${FIRSTPROJECT_DB_USER:-dev_firstproject}
      MYSQL_PASSWORD: ${FIRSTPROJECT_DB_PASSWORD:-dev_firstproject_pass}
    volumes:
      - firstproject_db_dev_data:/var/lib/mysql

  # User Database - Development Settings
  user-db:
    ports:
      - "${USER_DB_PORT:-3310}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_DB_ROOT_PASSWORD:-dev_user_root}
      MYSQL_DATABASE: ${USER_DB_NAME:-dev_Orders}
      MYSQL_USER: ${USER_DB_USER:-dev_user}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD:-dev_user_pass}
    volumes:
      - user_db_dev_data:/var/lib/mysql

  # HangFire Database - Development Settings
  hangfire-db:
    ports:
      - "${HANGFIRE_DB_PORT:-3311}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${HANGFIRE_DB_ROOT_PASSWORD:-dev_hangfire_root}
      MYSQL_DATABASE: ${HANGFIRE_DB_NAME:-dev_HangFire}
      MYSQL_USER: ${HANGFIRE_DB_USER:-dev_hangfire}
      MYSQL_PASSWORD: ${HANGFIRE_DB_PASSWORD:-dev_hangfire_pass}
    volumes:
      - hangfire_db_dev_data:/var/lib/mysql

  # ========================================
  # phpMyAdmin - Development Settings
  # ========================================
  phpmyadmin:
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: ${ADMIN_DB_CONTAINER_NAME:-admin-db},${CUSTOMERSERVICE_DB_CONTAINER_NAME:-customerservice-db},${FIRSTPROJECT_DB_CONTAINER_NAME:-firstproject-db},${USER_DB_CONTAINER_NAME:-user-db},${HANGFIRE_DB_CONTAINER_NAME:-hangfire-db}
      MYSQL_ROOT_PASSWORD: ${PHPMYADMIN_ROOT_PASSWORD:-dev_phpmyadmin_root}

  # ========================================
  # Application Services - Development Overrides
  # ========================================

  # Admin Service - Development Settings
  admin-service:
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://+:80
      
      # Development Database Configuration
      ConnectionStrings__DefaultConnection: Server=${ADMIN_DB_CONTAINER_NAME:-admin-db};Database=${ADMIN_DB_NAME:-dev_logs};User=${ADMIN_DB_USER:-dev_admin};Password=${ADMIN_DB_PASSWORD:-dev_admin_pass};SslMode=Preferred;
      ConnectionStrings__Connection: Server=${ADMIN_DB_CONTAINER_NAME:-admin-db};Database=${ADMIN_DB_NAME:-dev_logs};User=${ADMIN_DB_USER:-dev_admin};Password=${ADMIN_DB_PASSWORD:-dev_admin_pass};
      
      # Development JWT Settings
      JWT__Issuer: ${JWT_ISSUER:-http://localhost:9100}
      JWT__Audience: ${JWT_AUDIENCE:-http://localhost:9100}
      JWT__SecretKey: ${JWT_SECRET_KEY:-dev_jwt_secret_key_for_development_only_not_secure}
      
      # Development Admin Configuration
      Admin__SuperAdminEmail: ${ADMIN_SUPER_ADMIN_EMAIL:-admin@localhost}
      Admin__SuperAdminPassword: ${ADMIN_SUPER_ADMIN_PASSWORD:-DevAdmin123!}
      
      # Development CORS Configuration
      CORS__AllowedOrigins: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8090,http://localhost:9100}
    ports:
      - "${ADMIN_SERVICE_PORT:-5001}:80"
    volumes:
      - admin_logs_dev:/app/logs
      - ./Admin:/app/source:ro  # Mount source for hot reload (read-only)

  # CustomerService - Development Settings
  customerservice-service:
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://+:80
      
      # Development Database Configuration
      ConnectionStrings__DefaultConnection: Server=${CUSTOMERSERVICE_DB_CONTAINER_NAME:-customerservice-db};Database=${CUSTOMERSERVICE_DB_NAME:-dev_CustomerService};User=${CUSTOMERSERVICE_DB_USER:-dev_customerservice};Password=${CUSTOMERSERVICE_DB_PASSWORD:-dev_customerservice_pass};SslMode=Preferred;
      ConnectionStrings__Connection: Server=${CUSTOMERSERVICE_DB_CONTAINER_NAME:-customerservice-db};Database=${CUSTOMERSERVICE_DB_NAME:-dev_CustomerService};User=${CUSTOMERSERVICE_DB_USER:-dev_customerservice};Password=${CUSTOMERSERVICE_DB_PASSWORD:-dev_customerservice_pass};
      
      # Development JWT Settings
      JWT__Issuer: ${JWT_ISSUER:-http://localhost:9100}
      JWT__Audience: ${JWT_AUDIENCE:-http://localhost:9100}
      JWT__SecretKey: ${JWT_SECRET_KEY:-dev_jwt_secret_key_for_development_only_not_secure}
      
      # Development CORS Configuration
      CORS__AllowedOrigins: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8090,http://localhost:9100}
    ports:
      - "${CUSTOMERSERVICE_SERVICE_PORT:-5002}:80"
    volumes:
      - customerservice_uploads_dev:/app/uploads
      - ./CustomerService:/app/source:ro  # Mount source for hot reload (read-only)

  # FirstProject Service - Development Settings
  firstproject-service:
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://+:${FIRSTPROJECT_SERVICE_INTERNAL_PORT:-9100}
      PORT: ${FIRSTPROJECT_SERVICE_INTERNAL_PORT:-9100}
      
      # Development Database Configuration
      ConnectionStrings__DefaultConnection: Server=${FIRSTPROJECT_DB_CONTAINER_NAME:-firstproject-db};Database=${FIRSTPROJECT_DB_NAME:-dev_mainData};User=${FIRSTPROJECT_DB_USER:-dev_firstproject};Password=${FIRSTPROJECT_DB_PASSWORD:-dev_firstproject_pass};SslMode=Preferred;
      ConnectionStrings__Connection: Server=${FIRSTPROJECT_DB_CONTAINER_NAME:-firstproject-db};Database=${FIRSTPROJECT_DB_NAME:-dev_mainData};User=${FIRSTPROJECT_DB_USER:-dev_firstproject};Password=${FIRSTPROJECT_DB_PASSWORD:-dev_firstproject_pass};
      
      # Development JWT Settings
      JWT__Issuer: ${JWT_ISSUER:-http://localhost:9100}
      JWT__Audience: ${JWT_AUDIENCE:-http://localhost:9100}
      JWT__SecretKey: ${JWT_SECRET_KEY:-dev_jwt_secret_key_for_development_only_not_secure}
      
      # Development CORS Configuration
      CORS__AllowedOrigins: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8090,http://localhost:9100}
    ports:
      - "${FIRSTPROJECT_SERVICE_PORT:-9100}:${FIRSTPROJECT_SERVICE_INTERNAL_PORT:-9100}"
    volumes:
      - ./firstProject:/app/source:ro  # Mount source for hot reload (read-only)

  # User Service - Development Settings
  user-service:
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://+:80
      
      # Development Database Configuration
      ConnectionStrings__DefaultConnection: Server=${USER_DB_CONTAINER_NAME:-user-db};Database=${USER_DB_NAME:-dev_Orders};User=${USER_DB_USER:-dev_user};Password=${USER_DB_PASSWORD:-dev_user_pass};SslMode=Preferred;
      ConnectionStrings__Connection: Server=${USER_DB_CONTAINER_NAME:-user-db};Database=${USER_DB_NAME:-dev_Orders};User=${USER_DB_USER:-dev_user};Password=${USER_DB_PASSWORD:-dev_user_pass};
      ConnectionStrings__HangeFire: Server=${HANGFIRE_DB_CONTAINER_NAME:-hangfire-db};Database=${HANGFIRE_DB_NAME:-dev_HangFire};User=${HANGFIRE_DB_USER:-dev_hangfire};Password=${HANGFIRE_DB_PASSWORD:-dev_hangfire_pass};
      
      # Development JWT Settings
      JWT__Issuer: ${JWT_ISSUER:-http://localhost:9100}
      JWT__Audience: ${JWT_AUDIENCE:-http://localhost:9100}
      JWT__SecretKey: ${JWT_SECRET_KEY:-dev_jwt_secret_key_for_development_only_not_secure}
      
      # Development PayPal Configuration (Sandbox)
      PayPal__ClientId: ${PAYPAL_CLIENT_ID:-sandbox_client_id}
      PayPal__Secret: ${PAYPAL_SECRET:-sandbox_secret}
      PayPal__IsSandbox: ${PAYPAL_IS_SANDBOX:-true}
      
      # Development Email Configuration
      EmailConfiguration__From: ${EMAIL_FROM:-dev@localhost}
      EmailConfiguration__SmtpServer: ${EMAIL_SMTP_SERVER:-mailhog}
      EmailConfiguration__Port: ${EMAIL_PORT:-1025}
      EmailConfiguration__Username: ${EMAIL_USERNAME:-dev@localhost}
      EmailConfiguration__Password: ${EMAIL_PASSWORD:-dev_password}
      EmailConfiguration__UseSSL: ${EMAIL_USE_SSL:-false}
      
      # Development CORS Configuration
      CORS__AllowedOrigins: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8090,http://localhost:9100}
    ports:
      - "${USER_SERVICE_PORT:-5003}:80"
    volumes:
      - ./User:/app/source:ro  # Mount source for hot reload (read-only)

  # ========================================
  # Nginx - Development Settings
  # ========================================
  nginx:
    ports:
      - "${NGINX_HTTP_PORT:-8090}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"  # Different HTTPS port for dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl

  # ========================================
  # Development Tools
  # ========================================
  
  # MailHog for Email Testing in Development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${MAILHOG_CONTAINER_NAME:-mailhog}
    restart: unless-stopped
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"  # SMTP server
      - "${MAILHOG_WEB_PORT:-8025}:8025"   # Web UI
    networks:
      - takhlees-network

# ========================================
# Development Volumes
# ========================================
volumes:
  # Development database volumes (separate from production)
  admin_db_dev_data:
  customerservice_db_dev_data:
  firstproject_db_dev_data:
  user_db_dev_data:
  hangfire_db_dev_data:
  # Development application volumes
  admin_logs_dev:
  customerservice_uploads_dev: 